# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunUMISampling <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_Seurat2_RunUMISampling', PACKAGE = 'Seurat2', data, sample_val, upsample, display_progress)
}

RunUMISamplingPerCell <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_Seurat2_RunUMISamplingPerCell', PACKAGE = 'Seurat2', data, sample_val, upsample, display_progress)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_Seurat2_RowMergeMatrices', PACKAGE = 'Seurat2', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

LogNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call('_Seurat2_LogNorm', PACKAGE = 'Seurat2', data, scale_factor, display_progress)
}

FastMatMult <- function(m1, m2) {
    .Call('_Seurat2_FastMatMult', PACKAGE = 'Seurat2', m1, m2)
}

FastRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_Seurat2_FastRowScale', PACKAGE = 'Seurat2', mat, scale, center, scale_max, display_progress)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_Seurat2_Standardize', PACKAGE = 'Seurat2', mat, display_progress)
}

FastSparseRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_Seurat2_FastSparseRowScale', PACKAGE = 'Seurat2', mat, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_Seurat2_FastCov', PACKAGE = 'Seurat2', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_Seurat2_FastCovMats', PACKAGE = 'Seurat2', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_Seurat2_FastRBind', PACKAGE = 'Seurat2', mat1, mat2)
}

FastExpMean <- function(mat, display_progress) {
    .Call('_Seurat2_FastExpMean', PACKAGE = 'Seurat2', mat, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_Seurat2_FastLogVMR', PACKAGE = 'Seurat2', mat, display_progress)
}

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename) {
    .Call('_Seurat2_RunModularityClusteringCpp', PACKAGE = 'Seurat2', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call('_Seurat2_ComputeSNN', PACKAGE = 'Seurat2', nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call('_Seurat2_WriteEdgeFile', PACKAGE = 'Seurat2', snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call('_Seurat2_DirectSNNToFile', PACKAGE = 'Seurat2', nn_ranked, prune, display_progress, filename)
}

